version: '3.8'  

services:

 todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - my-network
    depends_on:
      - frontend


  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - frontend

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - frontend

networks:
  my-network:
    driver: bridge
