apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: k8s  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nabil2222/frontend
        ports:
        - containerPort: 8080

