apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
      - name: log-message-processor
        image: nabil2222/log-message-processor
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"   
        - name: REDIS_PORT
          value: "6379"   
        - name: REDIS_CHANNEL
          value: "log_messages"   
