apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: projet
spec:
  type: NodePort
  selector:
    app: log-message-processor
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30087
