apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: k8s
spec:
  type: ClusterIP
  selector:
    app: todos-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
