apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: k8s
spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083   
      targetPort: 8083   
