apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: nabil2222/auth-api
        ports:
        - containerPort: 8081  
        env:
        - name: AUTH_API_PORT
          value: "8081"
        - name: USERS_API_ADDRESS
          value: "http://users-api:8082"
        - name: JWT_SECRET
          value: "foo"   

      

