apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: nabil2222/todos-api
        ports:
        - containerPort: 8083

