apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: k8s  
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # External accessible port

