name: Build Microservices

on:
  push:
    branches:
      - build
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: 
          - frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
